# Generated by Django 4.1.4 on 2022-12-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertdata',
            name='photo',
            field=models.ImageField(default='', upload_to='static/studentimage'),
        ),
    ]
