# Generated by Django 4.1.4 on 2022-12-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regdata', '0003_alter_insertdata_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='passoutdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('btime', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('remfee', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='insertdata',
            name='photo',
            field=models.ImageField(default='', upload_to='static/studentimage'),
        ),
    ]
