# Generated by Django 4.1.4 on 2023-01-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regdata', '0004_passoutdata_alter_insertdata_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50)),
                ('remfee', models.CharField(max_length=50)),
                ('totalfee', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
