# Generated by Django 4.1.4 on 2023-01-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regdata', '0005_feedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50)),
                ('remfee', models.CharField(max_length=50)),
                ('totalfee', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('todate', models.CharField(max_length=50)),
            ],
        ),
    ]
